// Generated by gencpp from file odrive_interface/ArmKeyboard.msg
// DO NOT EDIT!


#ifndef ODRIVE_INTERFACE_MESSAGE_ARMKEYBOARD_H
#define ODRIVE_INTERFACE_MESSAGE_ARMKEYBOARD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace odrive_interface
{
template <class ContainerAllocator>
struct ArmKeyboard_
{
  typedef ArmKeyboard_<ContainerAllocator> Type;

  ArmKeyboard_()
    : header()
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , joint(0)
    , updown(0.0)
    , holdrelease(0.0)  {
    }
  ArmKeyboard_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , joint(0)
    , updown(0.0)
    , holdrelease(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef uint32_t _joint_type;
  _joint_type joint;

   typedef float _updown_type;
  _updown_type updown;

   typedef float _holdrelease_type;
  _holdrelease_type holdrelease;





  typedef boost::shared_ptr< ::odrive_interface::ArmKeyboard_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::odrive_interface::ArmKeyboard_<ContainerAllocator> const> ConstPtr;

}; // struct ArmKeyboard_

typedef ::odrive_interface::ArmKeyboard_<std::allocator<void> > ArmKeyboard;

typedef boost::shared_ptr< ::odrive_interface::ArmKeyboard > ArmKeyboardPtr;
typedef boost::shared_ptr< ::odrive_interface::ArmKeyboard const> ArmKeyboardConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::odrive_interface::ArmKeyboard_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::odrive_interface::ArmKeyboard_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::odrive_interface::ArmKeyboard_<ContainerAllocator1> & lhs, const ::odrive_interface::ArmKeyboard_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.joint == rhs.joint &&
    lhs.updown == rhs.updown &&
    lhs.holdrelease == rhs.holdrelease;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::odrive_interface::ArmKeyboard_<ContainerAllocator1> & lhs, const ::odrive_interface::ArmKeyboard_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace odrive_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::odrive_interface::ArmKeyboard_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::odrive_interface::ArmKeyboard_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::odrive_interface::ArmKeyboard_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::odrive_interface::ArmKeyboard_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::odrive_interface::ArmKeyboard_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::odrive_interface::ArmKeyboard_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::odrive_interface::ArmKeyboard_<ContainerAllocator> >
{
  static const char* value()
  {
    return "978d84a3bc6b3fd8840bb7afff707204";
  }

  static const char* value(const ::odrive_interface::ArmKeyboard_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x978d84a3bc6b3fd8ULL;
  static const uint64_t static_value2 = 0x840bb7afff707204ULL;
};

template<class ContainerAllocator>
struct DataType< ::odrive_interface::ArmKeyboard_<ContainerAllocator> >
{
  static const char* value()
  {
    return "odrive_interface/ArmKeyboard";
  }

  static const char* value(const ::odrive_interface::ArmKeyboard_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::odrive_interface::ArmKeyboard_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"uint32 joint\n"
"float32 updown\n"
"float32 holdrelease\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::odrive_interface::ArmKeyboard_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::odrive_interface::ArmKeyboard_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.joint);
      stream.next(m.updown);
      stream.next(m.holdrelease);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArmKeyboard_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::odrive_interface::ArmKeyboard_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::odrive_interface::ArmKeyboard_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "joint: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.joint);
    s << indent << "updown: ";
    Printer<float>::stream(s, indent + "  ", v.updown);
    s << indent << "holdrelease: ";
    Printer<float>::stream(s, indent + "  ", v.holdrelease);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ODRIVE_INTERFACE_MESSAGE_ARMKEYBOARD_H
